---
- name: Check ssh and password before proceeding
  tags:
    - always
  block:
    - name: Check ssh password first
      command: echo "ssh password correct"
      changed_when: false

    - name: Check sudo password first
      command: echo "sudo password correct"
      become: true
      become_user: root
      changed_when: false
