execute pathogen#infect()
syntax on

"set foldmethod=syntax"
set nowrap               " don"t wrap lines
set tabstop=4            " a tab is four spaces
set backspace=indent,eol,start " allow backspacing over everything in insert mode

set encoding=utf-8
set ambiwidth = "single"
set autoindent           " always set autoindenting on
set copyindent           " copy the previous indentation on autoindenting
set number               " always show line numbers
set shiftwidth=4         " number of spaces to use for autoindenting
set shiftround           " use multiple of shiftwidth when indenting with "<" and ">""
set showmatch            " set show matching parenthesis
set ignorecase           " ignore case when searching
set smartcase            " ignore case if search pattern is all lowercase, case-sensitive otherwise
set smarttab             " insert tabs on the start of a line according to shiftwidth, not tabstop
set hlsearch             " highlight search terms
set incsearch            " show search matches as you type"
set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set title                " change the terminal"s title
set visualbell           " don"t beep
set noerrorbells         " don"t beep"
set nobackup             " disable backups"
set noswapfile           " disable backups"
set spell
set mouse=nicr
setlocal spell spelllang=en_us
set expandtab

set list
set listchars=tab:>.,trail:.,extends:#,nbsp:. "mark whitespace"

" Leader Key to ","
let mapleader=","

" remappings
inoremap jj <ESC>
inoremap kk <ESC>

" ,ev to edit vim, ,sv to source vim
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

" map down and up to up next row and down next row
nnoremap j gj
nnoremap k gk

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Easy Tab navigation
nnoremap th :tabfirst<CR>
nnoremap tj :tabnext<CR>
nnoremap tk :tabprev<CR>
nnoremap tl :tablast<CR>
nnoremap tt :tabedit<Space>
nnoremap tn :tabnew<CR>:NERDTree<CR>
nnoremap tm :tabm<Space>
nnoremap td :tabclose<CR>

" Change snipmate trigger to ,Tab
" Makes it compatible with tab completion
imap <leader><tab> <Plug>snipMateNextOrTrigger
smap <leader><tab> <Plug>snipMateNextOrTrigger

" Turns on plugins
filetype plugin on

"Turns on automatic indent from plugins
filetype indent on
"allows empty .tex files to open as latex files
let g:Tex_flavor="latex"
" Change defualt tex output to PDF
let g:Tex_DefaultTargetFormat="pdf"
" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
let g:Tex_ViewRule_pdf="preview"
set grepprg=grep\ -nH\ $*

" Solarized Settings
set background=light
" This Sets Solarized theme values in VIM
"let g:solarized_termtrans=1
let g:solarized_termcolors=256
"let g:solarized_contrast="high"
"let g:solarized_visibility="high"

"Set vim Colorscheme
colorscheme solarized

" Syntastic Settings
let g:syntastic_mode_map={"mode": "active","active_filetypes": ["vim"],"passive_filetypes": []}"
let g:syntastic_check_on_open = 1 " Checks file when loaded into buffer
let g:syntastic_error_symbol="✗"
let g:syntastic_warning_symbol="W"
let g:jshint_highlight_color ="Red"
let g:syntastic_html_checkers = ['tidy']
let g:syntastic_html_tidy_ignore_errors = [" proprietary attribute \"ng-"]"]
let g:syntastic_json_checkers = ['jsonlint']
let g:syntastic_javascript_checkers = ['jshint', 'gjslint']

" Snipmate Settings
let g:snipMate = {}
let g:snipMate.scope_aliases = {}
let g:snipMate.scope_aliases['jsx'] = 'javascript,jsx'

" Set tabs to two spaces
function! TwoSpace()
  setlocal shiftwidth=2
  setlocal tabstop=2
  setlocal sts=2
  setlocal expandtab
endfunction

" Set bar at max width in accordance with Google style guide
" aka Closure linter
function! ClosureIt()
    setlocal textwidth=80
    setlocal colorcolumn=+1
    hi ColorColumn  ctermbg=246
    hi OverLength   ctermfg=125 ctermbg=250
    match OverLength /\%>80v.\+/
endfunction

" check for jsx using settings set by vim-jsx
function! JsxIt()
    if g:jsx_pragma_required && b:jsx_pragma_found
        let b:syntastic_checkers=['jsxhint']
    endif
endfunction

" Ignore camelCase words when spell checking
fun! IgnoreCamelCaseSpell()
  syn match CamelCase /\<[A-Z][a-z]\+[A-Z].\{-}\>/ contains=@NoSpell transparent
  syn cluster Spell add=CamelCase
endfun

autocmd BufRead,BufNewFile * :call IgnoreCamelCaseSpell()

augroup JavscriptG
  autocmd!
  autocmd BufRead *.js normal zR
  autocmd BufNewFile,BufReadPost *.js,*.jade,*.coffee,*.json,*.scss,*.sass,*.styl call TwoSpace()
  autocmd BufNewFile,BufReadPost *.js call ClosureIt()
  autocmd BufNewFile,BufReadPost *.js call JsxIt()
  autocmd BufNewFile,BufReadPost *.json set filetype=json
  autocmd BufNewFile,BufReadPost *.coffee setl foldmethod=indent nofoldenable "Auto collapse by indentation"
augroup END

" Parentheses colours using Solarized
let g:rbpt_colorpairs = [
  \ [ '13', '#6c71c4'],
  \ [ '5',  '#d33682'],
  \ [ '1',  '#dc322f'],
  \ [ '9',  '#cb4b16'],
  \ [ '3',  '#b58900'],
  \ [ '2',  '#859900'],
  \ [ '6',  '#2aa198'],
  \ [ '4',  '#268bd2'],
  \ ]

" Enable rainbow parentheses for all buffers
augroup rainbow_parentheses
  au!
  au VimEnter * RainbowParenthesesActivate
  au BufEnter * RainbowParenthesesLoadRound
  au BufEnter * RainbowParenthesesLoadSquare
  au BufEnter * RainbowParenthesesLoadBraces
augroup END

"folding is disabled by default but can be quickly toggled per-file by hitting zi"
augroup XmlG
  autocmd!
  " Remove whitespace markers in htmlxml
  autocmd filetype html,xml set listchars-=tab:>.
  " Set WSDL files using XML filetype
  autocmd BufNewFile,BufRead *.wsdl setlocal ft=xml
augroup END

augroup Snips
  autocmd!
  autocmd BufNewFile,BufReadPost *.snippets setlocal noet ci pi sts=0 sw=4 ts=4 listchars-=tab:>. listchars=tab:\|\ "
  autocmd BufNewFile,BufReadPost *.snippets hi SpecialKey ctermbg=NONE ctermfg=gray
augroup END

" Alias NERDTree to nerd
cnoreabbrev <expr> nerd ((getcmdtype() is# ":" && getcmdline() is# "nerd")?("NERDTreeToggle"):("nerd"))

" NERDTree show hidden files
let NERDTreeShowHidden=1
" Let NERDTree autoopen when vim is opened with no files
function! StartUp()
  if 0 == argc()
    NERDTree
  end
endfunction

augroup StartIt
  autocmd!
  autocmd BufNewFile,BufReadPost *.vimrc call TwoSpace()
  autocmd VimEnter * call StartUp()
augroup END

" Alias :UndotreeToggle to ent
cnoreabbrev <expr> ents ((getcmdtype() is# ":" && getcmdline() is# "ents")?("UndotreeToggle"):("ents"))

" Alias Helptags to rbHelp, This makes way more sense to me and will be
" easier to remember
cnoreabbrev <expr> rbHelp ((getcmdtype() is# ":" && getcmdline() is# "rbHelp")?("Helptags"):("rbHelp"))

" Alias sudo overwrite
cnoreabbrev <expr> sudowrite ((getcmdtype() is# ":" && getcmdline() is# "sudowrite")?(":w !sudo tee %"):("sudowrite"))

" easymotion mappings
nmap s <Plug>(easymotion-s2)
nmap t <Plug>(easymotnion-t2)

" easyMotion search
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)

" These `n` & `N` mappings are options. You do not have to map `n` & `N` to EasyMotion.
" Without these mappings, `n` & `N` works fine. (These mappings just provide
" different highlight method and have some other features )
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)
" Search in line
map <Leader>l <Plug>(easymotion-lineforward)
map <Leader>j <Plug>(easymotion-j)
map <Leader>k <Plug>(easymotion-k)
map <Leader>h <Plug>(easymotion-linebackward)

" Vim Airline
set laststatus=2
set ttimeoutlen=50
" Auto Display all buffers
"let g:airline_left_sep = '>'
"let g:airline_right_sep = '<'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#syntastic#enabled = 1
let g:airline_theme="badwolf"
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

let g:airline#extensions#tmuxline#enabled = 0
let g:tmuxline_powerline_separators=0

let g:tmuxline_preset={
    \ 'a': '#S',
    \ 'b': '#W',
    \ 'c': '#H',
    \ 'win': '#I #W',
    \ 'cwin': '#I #W',
    \ 'x': '%a',
    \ 'y': '#W %R',
    \ 'z': '#H',
    \ 'options':{'status-justify' : 'left'}}

let g:tmuxline_separators = {
    \ 'left' : '▶',
    \ 'left_alt': '>',
    \ 'right' : '◀',
    \ 'right_alt' : '<',
    \ 'space' : ' '}
" tmux clipboard workaround
set clipboard=unnamed

" JSON Syntax settings
let g:vim_json_syntax_concealcursor=""
let g:indentLine_noConcealCursor=""
" commands
" Convert double quotes to single quotes
command! SingleQ %s/"/'/g
command! DoubleQ %s/'/"/g

function! ConvertSpace()
  set ts=4 sts=4 noet
  retab!
  set ts=2 sts=2 et
  retab
endfunction
command! TabSpaceConvert call ConvertSpace()

function! RotateWindowsFunc()
  wincmd H
endfunction
command! RotateWindow call RotateWindowsFunc()
