---
- name: ensure user dirs
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  loop:
    - '{{ ansible_env.HOME }}/docs/notes/captainslog/'  # captains log command in shell/task.sh
    - '{{ ansible_env.HOME }}/.local/share/x11'  # x11 logging set up in zprofile
  tags:
    - user
    - folders
    - init

- name: make zsh default shell
  become: true
  user: name=berkeleytrue shell=/usr/bin/zsh
  tags:
    - init
    - user
    - zsh

- name: pacman colored output
  become: true
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    regexp: ^(.*)Color
    line: Color
  tags:
    - system
    - init
    - user

- name: ensure zshenv
  become: true
  ansible.builtin.copy:
    src: zshenv
    dest: /etc/zsh/zshenv
    backup: true
    owner: root
    mode: '0644'
  tags:
    - init
    - resources
    - zsh
    - files
    - user
