---
- name: Ensure user dirs
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  loop: '{{ user_space_dirs }}'
  tags:
    - user
    - folders
    - init

- name: Ensure user log files
  ansible.builtin.file:
    path: '{{ item }}'
    state: touch
    mode: 0644 # owner read/write, group read, world read
  loop:
    - '{{ user_space_files }}'

  tags:
    - user
    - files
    - init

- name: Make zsh default shell
  become: true
  become_user: root
  user:
    name: berkeleytrue
    shell: /usr/bin/zsh
  tags:
    - init
    - user
    - zsh

- name: Make pacman colored output
  become: true
  become_user: root
  lineinfile:
    dest: /etc/pacman.conf
    state: present
    regexp: ^(.*)Color
    line: Color
  tags:
    - system
    - init
    - user

- name: Ensure zshenv
  become: true
  become_user: root
  ansible.builtin.copy:
    src: zshenv
    dest: /etc/zsh/zshenv
    backup: true
    owner: root
    mode: '0644'
  tags:
    - init
    - resources
    - zsh
    - files
    - user

- name: Ensure Taskwarrior autosyncing
  ansible.builtin.cron:
    name: Sync taskwarrior
    minute: 0 # runs on evey 0 minute (hourly)
    job: /home/berkeleytrue/.config/task/hooks/cron-update.sh
  tags:
    - init
    - taskwarrior-cron

- name: Disable lightdm
  become: true
  become_user: root
  systemd:
    name: lightdm
    enabled: false
    state: stopped
  tags:
    - systemd

- name: Enable docker service
  become: true
  become_user: root
  systemd:
    name: docker
    enabled: true
    state: started
  tags:
    - systemd

- name: Ensure trackpad is set to natural scrolling
  become: true
  become_user: root
  lineinfile:
    dest: /etc/X11/xorg.conf.d/30-touchpad.conf
    search_string: '"NaturalScrolling" "true"'
    line: '    Option "NaturalScrolling" "true"'
    state: present
  tags:
    - natural-scrolling

- name: Ensure fennel treesitter is present
  git:
    repo: https://github.com/sogaiu/tree-sitter-fennel.git
    dest: '{{ user_space_ts_fennel }}'
    version: master
  tags:
    - fennel
