---
npm_global_packages:
  - n
  - neovim

  # clojurescript dev
  - shadow-cljs

  # package dev
  - commitizen
  - conventional-changelog-angular
  - conventional-changelog-cli
  - conventional-commits-detector
  - conventional-github-releaser
  - conventional-recommended-bump
  - cz-conventional-changelog
  - json
  - node-gyp
  - semver
  - trash

  # linting
  - eslint

  - typescript

  # lsp
  - javascript-typescript-langserver
  - typescript-eslint-parser
  - vscode-css-languageserver-bin
  - bash-language-server
  - dockerfile-language-server-nodejs
