#!/bin/bash
# bash/shell profile
# Run by login shells (bash)
#
# NOTE: Not run by zsh
# LightDM will run this before the window manager from /etc/lightdm/Xsession

# Add vi mappings to bash
set -o vi

[[ -s "$HOME/.config/shell/index.sh" ]] && source "$HOME/.config/shell/index.sh"
