---
- name: check if nvm is install
  shell: command -v nvm
  register: nvm_exists
  ignore_errors: true
  failed_when: false
  changed_when: not nvm_exists.rc

- name: download nvm install script
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh
    dest: ~/.cache/install-nvm.sh
    mode: "0755"
  when: nvm_exists.rc == 1

- name: execute install script
  shell: ~/.cache/install-nvm.sh
  when: nvm_exists.rc == 1

- name: Install node and set version
  shell: source {{ nvm_dir }}/nvm.sh && nvm install 12
  args:
    executable: /bin/bash
  when: nvm_exists.rc == 1
