---
- name: Update paks
  command: flatpak update --noninteractive
  timeout: 10
  changed_when: true
  tags:
    - update
    - flatpak
    - flatpak-update

- name: Install paks
  become: true
  become_user: root
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote | default('flathub') }}"
    state: present
  loop: "{{ paks }}"
  tags:
    - packages
    - flatpak
