---
- name: update
  shell:
    cmd: flatpak update --noninteractive
  tags:
    - update
    - flatpak

- name: install
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote | default('flathub') }}"
    state: present
  loop: "{{ paks }}"
  tags:
    - packages
    - flatpak
