---
- name: pak.update
  shell:
    cmd: flatpak update --noninteractive
  tags:
    - update
    - flatpak

- name: pak.install
  flatpak:
    name: "{{ item.name }}"
    remote: "{{ item.remote | default('flathub') }}"
    state: present
    method: user
  loop: "{{ paks }}"
  tags:
    - packages
    - flatpak
