---
- name: update system
  hosts: localhost
  become: true

  tasks:
    - name: full system update
      pacman:
        update_cache: true
        upgrade: true

    - name: ensure packages
      pacman:
        state: present
        update_cache: true
        name:
          - ansible-lint
          - yamllint
