#!/bin/sh
#
#
# Executed by startx (run your window manager from here)
# runs before window manager
# runs before xprofile
# must end by executing WM
# Keep light as possible
#
# run with startx in TTY
# i.e. $ startx ~/.config/x11/xinitrc

# NOTE: anything that takes long to run here will make it take longer to start WM
# NOTE: not run by lightdm

export DESKTOP_SESSION=plasma
export XSECURELOCK_NO_COMPOSITE=1 # xsecurelock doesn't work w/ picom
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_DATA_DIRS=$HOME/.nix-profile/share:$HOME/.share:"${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}"

X11_HOME=$XDG_CONFIG_HOME/x11
userresources=$X11_HOME/xresources
usermodmap=$X11_HOME/xmodmap
xprofile=$X11_HOME/xprofile
xbindrc=$HOME/.xbindkeysrc
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
XMONAD_EXEC=$HOME/.local/bin/xmonad-x86_64-linux
SESSION=${1:-xmonad}

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

if [ -f "$xbindrc" ]; then
  xbindkeys
fi

# source xprofile. This is done natively with some WM's but not xmonad
[ -f "$xprofile" ] && source $xprofile

# NOTE: programs in /etc/X11/xinit/xinitrc.d are sourced by /etc/lightdm/xsession in lightdm
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

case "$SESSION" in
kde)
  exec startplasma-x11
  ;;
*)
  exec $XMONAD_EXEC | sed 's/^/xmonad: /'

  # cleanup after xmonad exits
  echo "Xinit: xmonad exited. Cleaning up..."
  sysctemctl --user stop graphical-session.target
  systemctl --user stop graphical-session-pre.target
  # Wait until the units actually stop.
  while [ -n "$(systemctl --user --no-legend --state=deactivating list-units)" ]; do
    sleep 0.5
  done
  echo "Xinit: Good bye, Beautiful"
  ;;
esac
