#!/bin/sh
#
#
# Executed by startx (run your window manager from here)
# runs before window manager
# runs before xprofile
# must end by executing WM
# Keep light as possible
#
# run with startx in TTY
# i.e. $ startx ~/.config/x11/xinitrc

# NOTE: anything that takes long to run here will make it take longer to start WM
# NOTE: not run by lightdm
#
# TODO: set up for xmonad to use Ly


X11_HOME=$XDG_CONFIG_HOME
userresources=$X11_HOME/xresources
usermodmap=$X11_HOME/xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# NOTE: programs in /etc/X11/xinit/xinitrc.d are sourced by /etc/lightdm/xsession in lightdm
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec $(xmonad)
