#!/bin/sh
# X11 profile
#
# NOTE: Run by display manager

# make CapsLock behave like Ctrl:
/usr/bin/setxkbmap -option ctrl:nocaps &

# make short-pressed Ctrl behave like Escape:
/usr/bin/xcape -e 'Control_L=Escape' &

echo "starting xprofile apps" &

# start volumeicon
/usr/bin/volumeicon &

# start pulse audio conf
/usr/bin/pasystray &

# used for controlling system wide privileges
/usr/lib/polkit-kde-authentication-agent-1 &

#window composer
/usr/bin/picom -b &

# network manager
/usr/bin/nm-applet &

# notification daemon
/usr/bin/dunst &

# screen shot tool
/usr/bin/flameshot &

# bluetooth
/usr/bin/blueman-applet &

# private internet access vpn
/opt/piavpn/bin/pia-client &

# hide cursor when inactive
/usr/bin/unclutter -b &
