#!/bin/sh
# X11 profile
#
# NOTE: Run by lighdm

xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock &

# make CapsLock behave like Ctrl:
setxkbmap -option ctrl:nocaps &

# make short-pressed Ctrl behave like Escape:
xcape -e 'Control_L=Escape' &

echo "starting xprofile apps" &

# source $XDG_CONFIG_HOME/screenlayout/default.sh & # running from xmonad

# start volumeicon
volumeicon &

# start pulse audio conf
pasystray &

# used for controlling system wide privileges
/usr/lib/polkit-kde-authentication-agent-1 &

# desktop background manager
# nitrogen --restore & # running from xmonad

#window composer
picom -b --experimental-backends &

# network manager
nm-applet &

# manage power settings
xfce4-power-manager &

# notification daemon
dunst &

# clipboard manager
clipit &

# screen shot tool
flameshot &

# bluetooth
blueman-applet &

# touchpad support
# synclient NaturalScrolling=1 VertScrollDelta=-113 &

# private internet access vpn
/opt/piavpn/bin/pia-client &
frame &

# hide cursor when inactive
/bin/unclutter -b &
