---
- name: Update system, install packages, update system
  tags:
    - bootstrap
  block:
    - name: Ensure systemd-timesyncd is running
      become: true
      become_user: root
      systemd:
        name: systemd-timesyncd
        enabled: true
        state: started

    - name: Ensure mirrorlist
      become: true
      become_user: root
      copy:
        src: mirrorlist
        dest: /etc/pacman.d/mirrorlist
        backup: true
        owner: root
        mode: 0644
      tags: mirrorlist

    - name: Update system
      become: true
      become_user: root
      pacman:
        update_cache: true
        upgrade: true
      tags:
        - update
        - arch
        - pacman

    - name: Install packages
      become: true
      become_user: root
      pacman:
        name: '{{ packages }}'
        state: present
      tags:
        - arch
        - packages
        - pacman

    - name: Ensure files are absent
      become: true
      become_user: root
      file:
        path: '{{ file_to_delete }}'
        state: absent
      loop: '{{ base_files_to_delete }}'
      loop_control:
        loop_var: file_to_delete

    - name: Ensure getty folder exists
      become: true
      become_user: root
      file:
        path: /etc/systemd/system/getty@tty1.service.d/
        state: directory
        mode: 0644
      tags:
        - systemd
        - resources
        - folders

    - name: Ensure tty1 skips usernames
      become: true
      become_user: root
      ansible.builtin.copy:
        src: skip-username.conf
        dest: /etc/systemd/system/getty@tty1.service.d/skip-username.conf
        backup: true
        owner: root
        mode: '0644'
      tags:
        - systemd
        - resources
        - files

    - name: Ensure tt1 does not clear
      become: true
      become_user: root
      ansible.builtin.copy:
        src: noclear.conf
        dest: /etc/systemd/system/getty@tty1.service.d/noclear.conf
        backup: true
        owner: root
        mode: '0644'
      tags:
        - systemd
        - resources
        - files
