---
- name: Check if yay exists
  shell: command -v yay > /dev/null 2>&1
  changed_when: false
  register: does_yay_exists
  ignore_errors: true
  tags:
    - bootstrap
    - install-yay

- name: Install Yay from source
  when: does_yay_exists.rc
  tags:
    - bootstrap
    - install-yay
  block:
    - name: Check for base-devel packages
      become: true
      pacman:
        name: base-devel
        state: present

    - name: Check for git package
      become: true
      pacman:
        name: git
        state: present

    - name: Ensure dvl directory
      file:
        path: '{{ ansible_env.HOME }}/dvlpmnt'
        state: directory
        mode: 0755

    - name: Ensure yay directory
      file:
        path: '{{ ansible_env.HOME }}/dvlpmnt/yay'
        state: directory
        mode: 0755

    - name: Clone Yay repository
      git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: '{{ ansible_env.HOME }}/dvlpmnt/yay'
        version: master

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: true
      become_user: root
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: true
        validate: visudo -cf %s
        mode: 0644

    - name: Install Yay
      become: true
      become_user: aur_builder
      changed_when: true
      shell: >-
        echo "y" | makepkg --install
      args:
        chdir: '{{ ansible_env.HOME }}/dvlpmnt/yay'

- name: Remove user from sudoers
  become: true
  become_user: root
  ansible.builtin.file:
    path: /etc/sudoers.d/11-allow-makepkg-builder
    state: absent
