---
- name: Check if yay exists
  shell: command -v yay > /dev/null 2>&1 # needs to error in order to capture command status
  changed_when: false
  register: does_yay_exists
  ignore_errors: true
  tags:
    - bootstrap
    - install-yay

- name: Install Yay from source
  when: does_yay_exists.rc
  tags:
    - bootstrap
    - install-yay
  block:
    - name: Check for base-devel packages
      become: true
      become_user: root
      pacman:
        name: base-devel
        state: present

    - name: Check for git package
      become: true
      become_user: root
      pacman:
        name: git
        state: present

    - name: Ensure dvl directory
      file:
        path: '{{ ansible_env.HOME }}/dvlpmnt'
        state: directory
        mode: 0755

    - name: Ensure yay directory
      file:
        path: '{{ ansible_env.HOME }}/dvlpmnt/yay'
        state: directory
        mode: 0755

    - name: Clone Yay repository
      git:
        repo: https://aur.archlinux.org/yay-bin.git
        dest: '{{ ansible_env.HOME }}/dvlpmnt/yay'
        version: master

    - name: Create `aur_builder`
      include_role:
        name: aur_builder
        tasks_from: main

    - name: Install Yay
      become: true
      become_user: aur_builder
      changed_when: true
      shell: >-
        echo "y" | makepkg --install
      args:
        chdir: '{{ ansible_env.HOME }}/dvlpmnt/yay'

  always:
    - name: Cleanup `aur_builder`
      include_role:
        name: aur_builder
        tasks_from: cleanup
