---
- name: Running {{ item.name }} container
  block:
  - name: Ensure Dir {{ item.name }}
    file:
      path: '{{ container_home }}/{{ item.name }}'
      mode: 0755
      state: directory

  - name: Ensure compose file {{ item.name }}
    template:
      src: '{{ item.name }}/docker-compose.yml'
      dest: '{{ container_home }}/{{ item.name }}/docker-compose.yml'
      mode: 0644

  - name: Ensure volume exists {{ item.volume }}
    docker_volume:
      name: '{{ item.volume }}-db'

  - name: Ensure Container is up {{ item.name }}
    docker_compose:
      project_name: '{{ item.name }}'
      project_src: '{{ container_home }}/portainer'
