#!/bin/sh

set -e

stack build :xmonad
stack install :xmonad --local-bin-path bin/
cp bin/xmonad $HOME/.local/share/xmonad/xmonad-x86_64-linux
cp bin/xmonad $HOME/.local/bin/xmonad-x86_64-linux
cp bin/xmonad $HOME/.local/bin/xmonad
