---
packages:
  - ansible-lint
  - packer
  - terraform
  - vault
  - yamllint
  - yay

aur:
  - luarocks
  - terraform-lsp-git
  - terraform-provider-proxmox

pips:
  # for generating password hashes
  - passlib
