---
- name: fail2ban
  tags:
    - fail2ban
    - user

  block:
    - name: Install
      become: true
      become_user: root
      package:
        name: fail2ban
        state: present

    - name: Make slack notification action
      become: true
      become_user: root
      template:
        src: slack-notify.conf
        dest: /etc/fail2ban/action.d/slack-notify.conf
        mode: 0644
      notify:
        - Restart fail2ban

    - name: Apply jail.local
      become: true
      become_user: root
      copy:
        src: jail.local
        dest: /etc/fail2ban/jail.local
        mode: 0644
      notify:
        - Restart fail2ban

    - name: Enable fail2ban
      become: true
      become_user: root
      systemd:
        name: fail2ban
        enabled: true
