(module init
  {require-macros [macros]})

(require :plugins.nerd-commenter)
(require :plugins.scroll-fix)
(require :plugins.sexp)
(require :plugins.defx)
(require :plugins.fzf)
(require :plugins.accents)
(require :plugins.markdown)
(require :plugins.corpus)
(require :plugins.tree-sitter)
(require :plugins.colors)
(require :plugins.runtime-utils)
(require :plugins.indent-guides)
(require :plugins.packer)
(require :plugins.telescope)
