---
- name: Install, update, and manage AUR packages
  tags:
    - aur
    - packages
  block:
    - name: Create `aur_builder`
      include_role:
        name: aur_builder
        tasks_from: main

    - name: Update aur
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        aur_only: true
        upgrade: true
      tags:
        - update

    - name: Install aur packages
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        name: '{{ aur }}'
        state: present
        aur_only: true
      tags:
        - install-aur-packages

  always:
    - name: Cleanup `aur_builder`
      include_role:
        name: aur_builder
        tasks_from: cleanup
