---
- name: update
  shell:
    cmd: "python3 -m pip install --user --upgrade {{ item }}"
  loop: "{{ pips }}"
  tags:
    - python
    - update

- name: install
  ansible.builtin.pip:
    name: "{{ pips }}"
    state: present
  tags:
    - python
    - packages
