---
# - name: Update pip packages
#   command: python3 -m pip install --user --upgrade {{ item }}
#   loop: '{{ pips }}'
#   changed_when: true
#   tags:
#     - python
#     - update

- name: Install pip packages
  ansible.builtin.pip:
    name: '{{ pips }}'
    state: present
  tags:
    - python
    - packages
