---
- name: Update pip packages
  anbsible.builtin.pip:
    name: '{{ pips }}'
    state: latest
  tags:
    - python
    - update

- name: Install pip packages
  ansible.builtin.pip:
    name: '{{ pips }}'
    state: present
  tags:
    - python
    - packages
