---
# accessLog:
#   filePath: /var/log/access.log
#   format: json
#
#   fields:
#     defaultMode: drop
#     names:
#       RouterName: keep
#       ServiceName: keep
#       RequestAddr: keep
#       RequestHost: keep
#       RequestMethod: keep
#       RequestPath: keep
#       RequestProtocol: keep
#       RequestScheme: keep
#       ClientHost: keep
#       OriginStatus: keep
log:
  level: INFO
  filePath: /var/log/traefik.log

api:
  dashboard: true
  debug: true
  insecure: true

entrypoints:
  web:
    address: :80

  secureweb:
    address: :443

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false

  file:
    filename: /config.yml
