---
- name: base-os.full system update
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: base-os.aur update
  aur:
    aur_only: true
    upgrade: true

- name: base-os.ensure packages
  become: true
  pacman:
    name: "{{ packages }}"
    state: present

- name: base-os.ensure aur packages
  aur:
    name: "{{ aur }}"
    state: present

- name: base-os.install pip packages
  pip:
    name: "{{ pips }}"
    state: present
